package com.neuedu.pojo;

import java.util.Date;

public class ProductKillOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_kill_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_kill_order.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_kill_order.product_kill_id
     *
     * @mbg.generated
     */
    private Integer productKillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_kill_order.order_no
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_kill_order.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_kill_order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_kill_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_kill_order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill_order.id
     *
     * @return the value of product_kill_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill_order.id
     *
     * @param id the value for product_kill_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill_order.product_id
     *
     * @return the value of product_kill_order.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill_order.product_id
     *
     * @param productId the value for product_kill_order.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill_order.product_kill_id
     *
     * @return the value of product_kill_order.product_kill_id
     *
     * @mbg.generated
     */
    public Integer getProductKillId() {
        return productKillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill_order.product_kill_id
     *
     * @param productKillId the value for product_kill_order.product_kill_id
     *
     * @mbg.generated
     */
    public void setProductKillId(Integer productKillId) {
        this.productKillId = productKillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill_order.order_no
     *
     * @return the value of product_kill_order.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill_order.order_no
     *
     * @param orderNo the value for product_kill_order.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill_order.user_id
     *
     * @return the value of product_kill_order.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill_order.user_id
     *
     * @param userId the value for product_kill_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill_order.status
     *
     * @return the value of product_kill_order.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill_order.status
     *
     * @param status the value for product_kill_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill_order.create_time
     *
     * @return the value of product_kill_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill_order.create_time
     *
     * @param createTime the value for product_kill_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill_order.update_time
     *
     * @return the value of product_kill_order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill_order.update_time
     *
     * @param updateTime the value for product_kill_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}