package com.neuedu.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ProductKill implements Serializable {

    private Integer id;
    private Integer productId;
    private BigDecimal killPrice;
    private Integer total;
    private Date startTime;
    private Date endTime;
    private Integer isActive;
    private Date createTime;
    private Date updateTime;
    private Integer canKill;
    private String productName;

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Integer getCanKill() {
        return canKill;
    }

    public void setCanKill(Integer canKill) {
        this.canKill = canKill;
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill.id
     *
     * @param id the value for product_kill.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill.product_id
     *
     * @return the value of product_kill.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill.product_id
     *
     * @param productId the value for product_kill.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill.kill_price
     *
     * @return the value of product_kill.kill_price
     *
     * @mbg.generated
     */
    public BigDecimal getKillPrice() {
        return killPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill.kill_price
     *
     * @param killPrice the value for product_kill.kill_price
     *
     * @mbg.generated
     */
    public void setKillPrice(BigDecimal killPrice) {
        this.killPrice = killPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill.total
     *
     * @return the value of product_kill.total
     *
     * @mbg.generated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill.total
     *
     * @param total the value for product_kill.total
     *
     * @mbg.generated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill.start_time
     *
     * @return the value of product_kill.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill.start_time
     *
     * @param startTime the value for product_kill.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill.end_time
     *
     * @return the value of product_kill.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill.end_time
     *
     * @param endTime the value for product_kill.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill.is_active
     *
     * @return the value of product_kill.is_active
     *
     * @mbg.generated
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill.is_active
     *
     * @param isActive the value for product_kill.is_active
     *
     * @mbg.generated
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill.create_time
     *
     * @return the value of product_kill.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill.create_time
     *
     * @param createTime the value for product_kill.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_kill.update_time
     *
     * @return the value of product_kill.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_kill.update_time
     *
     * @param updateTime the value for product_kill.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "ProductKill{" +
                "id=" + id +
                ", productId=" + productId +
                ", killPrice=" + killPrice +
                ", total=" + total +
                ", startTime=" + startTime +
                ", endTime=" + endTime +
                ", isActive=" + isActive +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", canKill=" + canKill +
                ", productName='" + productName + '\'' +
                '}';
    }
}