package com.neuedu.dao;

import com.google.common.collect.Lists;
import com.neuedu.pojo.Order;
import com.neuedu.pojo.OrderItem;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);
    /**
     * 根据订单号查订单信息
     */
    Order findOrderByOrderNo(@Param("orderNo") Long orderNo);
    /**
     * 根据订单号修改订单
     */
    int updateOrderStatusAndPaymentTimeByOrderNo(@Param("order") Order order);
    /**
     * 根据用户id查询所有订单
     */
    List<Order> findAllOrderByUserId(@Param("userId") Integer userId);

    List<Order> findOrderListByStatus(@Param("userId")Integer userId,@Param("status") Integer status);

    int getAllOrderCount();

    int getOrderCountBystatus(@Param("status")Integer status);

    List<Order> findOrderBystatus(@Param("status")Integer status);


}