package com.neuedu.dao;

import com.neuedu.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Product record);

    int updateStatuById(@Param("id") Integer productId,@Param("status") Integer status);

    List<Product> findProductByNameAndId(@Param("productId") Integer productId,
                                         @Param("productName") String productName);

    List<Product> findProductByName(@Param("productName")String productName,
                                    @Param("status")Integer status);

    /**
     * 扣库存
     */
    int reduceStock(@Param("productId") Integer productId, @Param("stock")Integer stock);
    /**
     * 返回热销产品
     */
    List<Product> findHotProduct();

    /**
     * 新品
     * @return
     */
    List<Product> findNewProduct();

    List<Product> findProductListByCategory(@Param("categoryId")Integer categoryId);
    //通过类别查询返回总数
    int findCountBycategory(@Param("categoryId")Integer categoryId);

    int findProductCount();

    int getCountByProductName(@Param("productId") Integer productId,
                              @Param("productName") String productName);

    int getCountByProductNameAndStatus(@Param("productId")Integer productId, @Param("productName")String productName);

    List<Product> findProductByNameAndIdAndStatus(@Param("productId")Integer productId, @Param("productName")String productName);
}