server:
  #改端口号
  port: 8080
  #改项目路径  此时访问localhost:8888/springboot才可以访问项目
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf8
      username: root
      password: "root"
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  thymeleaf:
    mode: HTML5

  mvc:
    static-path-pattern: /static/**
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
pagehelper:
  helper-dialect: mysql #分页插件会自动检测当前的数据库链接
  reasonable: true #分页合理化参数，默认值为 false 。当该参数设置为 true 时， pageNum<=0 时会查询第一页， pageNum>pages （超过总数时），会查询最后一页。默认 false 时，直接根据参数进行查询。
  support-methods-arguments: true #分页插件会从查询方法的参数值中，自动根据 params 配置的字段中取值，查找到合适的值时就会自动分页
  params: countSql
logging:
  level:
    com.neuedu.dao: debug


###redis连接池参数
redis:
  max:
    total: 8  #最大连接数
    idle: 8   #最大空闲连接数
  min:
    idle: 2   #最小空闲连接数
  test:
    borrow: true
    return: true
  ip: 101.37.78.184
  port: 5379
  password: Hyc5670526
  timeout: 2000
  host : redis://101.37.78.184:5379
